# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1920486df84a49ee0ff78e104a343853e1947532badb257351bbd7dde4567aa64cf0cf1084419e6bface95c92095a08313721db7d7be50e89f59f6341e7abef

test:
  secret_key_base: 1931ea05bb18c0bced6508ee32f711e9045e281ad040a28afb6d6ecc3f8ef646912032d48dec16dbe699aa6e212d5f6b4ddc1dc0a5f5d47ff3a1224e831ce5d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
